[build]
  command = "yarn build || { cat /opt/buildhome/.yarn/_logs/* ; sleep 30 ; false; }"
  publish = "public/"

[build.environment]
  RUBY_VERSION = "2.6.2"
  NODE_VERSION = "12.16.1"
  NPM_VERSION = "6.13.4"
  YARN_VERSION = "1.22.10"
