[build]
  command = "yarn build || { cat /opt/buildhome/.npm/_logs/* ; sleep 30 ; false; }"
  publish = "public/"

[build.environment]
  RUBY_VERSION = "2.6.2"
  NODE_VERSION = "14.15.1"
  YARN_VERSION = "1.22.10"